contact_links:
- name: ğŸ™‹ğŸ¾ Question
  url: https://github.com/tjololo/hello-actions/discussions/categories/q-a
  about: If you have a question for me open a Q-A Discussion
- name: ğŸ¤” Request for comment
  url: https://github.com/tjololo/hello-actions/discussions/categories/request-for-comments
  about: Create a RFC for a large enhancement or change in my solution
